version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: зависимости
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: контейнер
  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: weekly
    commit-message:
      prefix: инфраструктура
  - package-ecosystem: terraform
    directory: /infra/bootstrap
    schedule:
      interval: weekly
    commit-message:
      prefix: инфраструктура
