apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tradingmaster
  namespace: tradingmaster
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tradingmaster
