apiVersion: v1
kind: Service
metadata:
  name: tradingmaster
  namespace: tradingmaster
  labels:
    app.kubernetes.io/name: tradingmaster
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tradingmaster
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
