apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tradingmaster
resources:
  - service-monitor.yaml
  - prometheus-rule.yaml
configMapGenerator:
  - name: tradingmaster-grafana-dashboard
    files:
      - tradingmaster-safety.json=grafana/tradingmaster-safety.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
